name: check-and-publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "yarn"
      - run: yarn install
      - run: |
          # add node_modules/.bin to PATH
          export PATH=$(pwd)/node_modules/.bin:$PATH
          # run the pre-push hook directly
          bash .husky/pre-push
      - run: yarn test:integration --run --reporter basic
      - run: yarn test:e2e --run --reporter basic

  publish:
    needs: run-checks
    name: publish to npm
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: disable husky
        run: npm pkg delete scripts.prepare
      - name: install
        run: yarn install
      - name: build
        run: yarn build
      - name: package
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
