name: sonar

on:
  workflow_run:
    branches:
      - main
    workflows: ['checks']
    types:
      - completed

jobs:
  run-checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v4
      with:
        node-version: 22
    - run: yarn install
    - run: rm -rf coverage && yarn vitest run --coverage
    - uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.organization=${{ secrets.SONAR_ORG }}
          -Dsonar.projectKey=${{ secrets.SONAR_PROJECT }}
          -Dsonar.language=ts
          -Dsonar.javascript.lcov.reportPaths=./coverage/lcov.info
          -Dsonar.sources=./src
          -Dsotar.tests=./tests
          -Dsonar.coverage.exclusions=
